# Generated by Django 6.0.4 on 2026-05-16 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_personaltodo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
        migrations.AddField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                related_name="tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
